# Generated by Django 4.2.10 on 2024-03-02 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_itenssaida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saidaavulsa',
            options={'verbose_name_plural': 'Itens Saidas Avulsa'},
        ),
    ]
