# Generated by Django 4.2.10 on 2024-03-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_saidaavulsa_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignado',
            name='material',
            field=models.ManyToManyField(blank=True, to='core.material'),
        ),
        migrations.AlterField(
            model_name='itenssaida',
            name='material',
            field=models.ManyToManyField(blank=True, to='core.material'),
        ),
        migrations.AlterField(
            model_name='saidaavulsa',
            name='material',
            field=models.ManyToManyField(blank=True, to='core.material'),
        ),
    ]
