# Generated by Django 4.2.10 on 2024-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_consignado_material_alter_itenssaida_material_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itenssaida',
            options={'verbose_name_plural': 'Itens Saidas Avulsa'},
        ),
        migrations.AlterModelOptions(
            name='saidaavulsa',
            options={'verbose_name_plural': 'Saidas Avulsa'},
        ),
        migrations.RemoveField(
            model_name='itenssaida',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='saidaavulsa',
            name='material',
        ),
        migrations.AlterField(
            model_name='itenssaida',
            name='material',
            field=models.ManyToManyField(to='core.material'),
        ),
    ]
