# Generated by Django 4.2.10 on 2024-03-02 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_itenssaida_options_alter_saidaavulsa_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenssaida',
            name='material',
        ),
        migrations.AddField(
            model_name='itenssaida',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.material'),
        ),
    ]
