# Generated by Django 4.2.10 on 2024-03-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_itenssaida_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaavulsa',
            name='itensSaida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.itenssaida'),
        ),
    ]
